services:
  - type: web
    name: hatamlservice
    runtime: python
    pythonVersion: 3.11
    buildCommand: pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port 5000
    envVars:
      - key: PORT
        value: 5000
      - key: HOST
        value: 0.0.0.0
      - key: RELOAD
        value: false
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PIP_DEFAULT_TIMEOUT
        value: 1000
      - key: PIP_RETRIES
        value: 10
